### ISSUE TITLE
Untangle x-editable requires

### ISSUE THREAD

**Issue by dometto** [repotag/repotag#13]
X-editable is currently being required in:
- `x-editable.js`
- `application.js.rb`

I think `x-editable.js` can go, if we require `admin/x-editable.js.coffee` from `admin.js`. But do we need any stuff in `admin/x-editable.js.coffee` outside the admin namespace as well? In that case we should split that file up in an admin-specific and application-general .js file. That way the separate include tag for x-editable in the layout files can go.

Not sure that this will solve the problem mentioned in #3 as I'm not seeing that locally, but at least it will make debugging simpler.

**Comment by bartkamphorst** [comment]
> But do we need any stuff in admin/x-editable.js.coffee outside the admin namespace as well?

We do, as user settings views also use x-editable.

**Comment by bartkamphorst** [comment]
See https://github.com/repotag/repotag/commit/c4cb24b9c025e20a8636bdcf76be7b9f76265139 .

**Comment by dometto** [comment]
:+1:

**Comment by bartkamphorst** [comment]
Seems like this resolves the other (deployment) issue as well! More later.
