### ISSUE TITLE
 Errno::ECONNREFUSED on new repository

### ISSUE THREAD

**Issue by dometto** [repotag/repotag#7]
When creating a new repository I get this error:

```
Errno::ECONNREFUSED at /repositories
Connection refused - Connection refused
```

From `HookMailer#send_confirmation_email`, `app/controllers/repositories_controller.rb:265`. The repository is created successfully, but the app shouldn't crash like this if SMTP is unavailable.

**Comment by bartkamphorst** [comment]
I turned this flag on in development: `config.action_mailer.raise_delivery_errors = true` (in `config/environments/development.rb`).

**Comment by dometto** [comment]
Makes sense. I think we should just rescue the error in `ApplicationController` and flash an alert or notice.

**Comment by bartkamphorst** [comment]
Good idea. It's a little bit tricky however to make a generic redirect statement. We can do

``` ruby
redirect_to :back
```

and this works nicely for the SMTP settings page, but less so for the repository#new page (as it sends you back to the form, even though the repo was created). Perhaps an error page with a helpful description is best?

**Comment by dometto** [comment]
What happens when we dont redirect but just flash something? Will it redirect to whatever the controller redirects to?

**Comment by bartkamphorst** [comment]
No, this will leave you in no man's land unfortunately (empty page). This is what I'm working with in ApplicationController:

``` ruby
rescue_from(Errno::ECONNREFUSED) do |e|
    flash[:warning] = 'SMTP connection failed.'
    redirect_to :back
end
```

**Comment by dometto** [comment]
I think this approach is fine for now. :)
