### ISSUE TITLE
Default settings for clone URL

### ISSUE THREAD

**Issue by dometto** [repotag/repotag#8]
In my dev setup, the clone URL looks like this:

![screen shot 2015-08-30 at 18 40 53](https://cloud.githubusercontent.com/assets/147111/9568347/3551d7f6-4f47-11e5-8be1-146a590f7bfa.png)

If no URL settings are available, I think the protocol/host/port should be guessed from the rack env or something. Maybe rails has helpers for this.

**Comment by bartkamphorst** [comment]
Default settings would of course also help.

**Comment by bartkamphorst** [comment]
Default settings have been added to `config/initializers/app_defaults.rb` in 647a8d2b77921cde4116cf70da1f2b5ca6176654.
